<?php

namespace CurrencyConversion\Enums;

enum Currency: string
{
    case  EUR = 'EUR';
    case  AED = 'AED';
    case  AFN = 'AFN';
    case  ALL = 'ALL';
    case  AMD = 'AMD';
    case  ANG = 'ANG';
    case  AOA = 'AOA';
    case  ARS = 'ARS';
    case  AUD = 'AUD';
    case  AWG = 'AWG';
    case  AZN = 'AZN';
    case  BAM = 'BAM';
    case  BBD = 'BBD';
    case  BDT = 'BDT';
    case  BGN = 'BGN';
    case  BHD = 'BHD';
    case  BIF = 'BIF';
    case  BMD = 'BMD';
    case  BND = 'BND';
    case  BOB = 'BOB';
    case  BRL = 'BRL';
    case  BSD = 'BSD';
    case  BTN = 'BTN';
    case  BWP = 'BWP';
    case  BYN = 'BYN';
    case  BZD = 'BZD';
    case  CAD = 'CAD';
    case  CDF = 'CDF';
    case  CHF = 'CHF';
    case  CLP = 'CLP';
    case  CNY = 'CNY';
    case  COP = 'COP';
    case  CRC = 'CRC';
    case  CUP = 'CUP';
    case  CVE = 'CVE';
    case  CZK = 'CZK';
    case  DJF = 'DJF';
    case  DKK = 'DKK';
    case  DOP = 'DOP';
    case  DZD = 'DZD';
    case  EGP = 'EGP';
    case  ERN = 'ERN';
    case  ETB = 'ETB';
    case  FJD = 'FJD';
    case  FKP = 'FKP';
    case  FOK = 'FOK';
    case  GBP = 'GBP';
    case  GEL = 'GEL';
    case  GGP = 'GGP';
    case  GHS = 'GHS';
    case  GIP = 'GIP';
    case  GMD = 'GMD';
    case  GNF = 'GNF';
    case  GTQ = 'GTQ';
    case  GYD = 'GYD';
    case  HKD = 'HKD';
    case  HNL = 'HNL';
    case  HRK = 'HRK';
    case  HTG = 'HTG';
    case  HUF = 'HUF';
    case  IDR = 'IDR';
    case  ILS = 'ILS';
    case  IMP = 'IMP';
    case  INR = 'INR';
    case  IQD = 'IQD';
    case  IRR = 'IRR';
    case  ISK = 'ISK';
    case  JEP = 'JEP';
    case  JMD = 'JMD';
    case  JOD = 'JOD';
    case  JPY = 'JPY';
    case  KES = 'KES';
    case  KGS = 'KGS';
    case  KHR = 'KHR';
    case  KID = 'KID';
    case  KMF = 'KMF';
    case  KRW = 'KRW';
    case  KWD = 'KWD';
    case  KYD = 'KYD';
    case  KZT = 'KZT';
    case  LAK = 'LAK';
    case  LBP = 'LBP';
    case  LKR = 'LKR';
    case  LRD = 'LRD';
    case  LSL = 'LSL';
    case  LYD = 'LYD';
    case  MAD = 'MAD';
    case  MDL = 'MDL';
    case  MGA = 'MGA';
    case  MKD = 'MKD';
    case  MMK = 'MMK';
    case  MNT = 'MNT';
    case  MOP = 'MOP';
    case  MRU = 'MRU';
    case  MUR = 'MUR';
    case  MVR = 'MVR';
    case  MWK = 'MWK';
    case  MXN = 'MXN';
    case  MYR = 'MYR';
    case  MZN = 'MZN';
    case  NAD = 'NAD';
    case  NGN = 'NGN';
    case  NIO = 'NIO';
    case  NOK = 'NOK';
    case  NPR = 'NPR';
    case  NZD = 'NZD';
    case  OMR = 'OMR';
    case  PAB = 'PAB';
    case  PEN = 'PEN';
    case  PGK = 'PGK';
    case  PHP = 'PHP';
    case  PKR = 'PKR';
    case  PLN = 'PLN';
    case  PYG = 'PYG';
    case  QAR = 'QAR';
    case  RON = 'RON';
    case  RSD = 'RSD';
    case  RUB = 'RUB';
    case  RWF = 'RWF';
    case  SAR = 'SAR';
    case  SBD = 'SBD';
    case  SCR = 'SCR';
    case  SDG = 'SDG';
    case  SEK = 'SEK';
    case  SGD = 'SGD';
    case  SHP = 'SHP';
    case  SLE = 'SLE';
    case  SLL = 'SLL';
    case  SOS = 'SOS';
    case  SRD = 'SRD';
    case  SSP = 'SSP';
    case  STN = 'STN';
    case  SYP = 'SYP';
    case  SZL = 'SZL';
    case  THB = 'THB';
    case  TJS = 'TJS';
    case  TMT = 'TMT';
    case  TND = 'TND';
    case  TOP = 'TOP';
    case  TRY = 'TRY';
    case  TTD = 'TTD';
    case  TVD = 'TVD';
    case  TWD = 'TWD';
    case  TZS = 'TZS';
    case  UAH = 'UAH';
    case  UGX = 'UGX';
    case  USD = 'USD';
    case  UYU = 'UYU';
    case  UZS = 'UZS';
    case  VES = 'VES';
    case  VND = 'VND';
    case  VUV = 'VUV';
    case  WST = 'WST';
    case  XAF = 'XAF';
    case  XCD = 'XCD';
    case  XDR = 'XDR';
    case  XOF = 'XOF';
    case  XPF = 'XPF';
    case  YER = 'YER';
    case  ZAR = 'ZAR';
    case  ZMW = 'ZMW';
    case  ZWL = 'ZWL';

    /**
     * Get the symbol of the currency
     *
     * @return string
     */
    public function getSymbol(): string
    {
        return match ($this) {
            self::EUR => '€',
            self::AED => 'د.إ',
            self::AFN => '؋',
            self::ALL => 'L',
            self::AMD => '֏',
            self::ANG => 'ƒ',
            self::AOA => 'Kz',
            self::ARS => '$',
            self::AUD => '$',
            self::AWG => 'ƒ',
            self::AZN => '₼',
            self::BAM => 'KM',
            self::BBD => '$',
            self::BDT => '৳',
            self::BGN => 'лв',
            self::BHD => '.د.ب',
            self::BIF => 'FBu',
            self::BMD => '$',
            self::BND => '$',
            self::BOB => 'Bs.',
            self::BRL => 'R$',
            self::BSD => '$',
            self::BTN => 'Nu.',
            self::BWP => 'P',
            self::BYN => 'Br',
            self::BZD => '$',
            self::CAD => '$',
            self::CDF => 'FC',
            self::CHF => 'CHF',
            self::CLP => '$',
            self::CNY => '¥',
            self::COP => '$',
            self::CRC => '₡',
            self::CUP => '$',
            self::CVE => '$',
            self::CZK => 'Kč',
            self::DJF => 'Fdj',
            self::DKK => 'kr',
            self::DOP => '$',
            self::DZD => 'دج',
            self::EGP => 'E£',
            self::ERN => 'Nfk',
            self::ETB => 'Br',
            self::FJD => '$',
            self::FKP => '£',
            self::FOK => 'kr',
            self::GBP => '£',
            self::GEL => '₾',
            self::GGP => '£',
            self::GHS => 'GH₵',
            self::GIP => '£',
            self::GMD => 'D',
            self::GNF => 'FG',
            self::GTQ => 'Q',
            self::GYD => '$',
            self::HKD => '$',
            self::HNL => 'L',
            self::HRK => 'kn',
            self::HTG => 'G',
            self::HUF => 'Ft',
            self::IDR => 'Rp',
            self::ILS => '₪',
            self::IMP => '£',
            self::INR => '₹',
            self::IQD => 'ع.د',
            self::IRR => '﷼',
            self::ISK => 'kr',
            self::JEP => '£',
            self::JMD => '$',
            self::JOD => 'د.ا',
            self::JPY => '¥',
            self::KES => 'KSh',
            self::KGS => 'с',
            self::KHR => '៛',
            self::KID => '$',
            self::KMF => 'CF',
            self::KRW => '₩',
            self::KWD => 'د.ك',
            self::KYD => '$',
            self::KZT => '₸',
            self::LAK => '₭',
            self::LBP => 'ل.ل',
            self::LKR => 'Rs',
            self::LRD => '$',
            self::LSL => 'L',
            self::LYD => 'ل.د',
            self::MAD => 'د.م.',
            self::MDL => 'L',
            self::MGA => 'Ar',
            self::MKD => 'ден',
            self::MMK => 'K',
            self::MNT => '₮',
            self::MOP => 'P',
            self::MRU => 'UM',
            self::MUR => '₨',
            self::MVR => 'Rf',
            self::MWK => 'MK',
            self::MXN => '$',
            self::MYR => 'RM',
            self::MZN => 'MT',
            self::NAD => '$',
            self::NGN => '₦',
            self::NIO => 'C$',
            self::NOK => 'kr',
            self::NPR => '₨',
            self::NZD => '$',
            self::OMR => 'ر.ع.',
            self::PAB => 'B/.',
            self::PEN => 'S/.',
            self::PGK => 'K',
            self::PHP => '₱',
            self::PKR => '₨',
            self::PLN => 'zł',
            self::PYG => '₲',
            self::QAR => 'ر.ق',
            self::RON => 'lei',
            self::RSD => 'дин',
            self::RUB => '₽',
            self::RWF => 'FRw',
            self::SAR => 'ر.س',
            self::SBD => '$',
            self::SCR => 'SR',
            self::SDG => 'ج.س.',
            self::SEK => 'kr',
            self::SGD => '$',
            self::SHP => '£',
            self::SLE => 'Le',
            self::SLL => 'Le',
            self::SOS => 'Sh',
            self::SRD => '$',
            self::SSP => '£',
            self::STN => 'Db',
            self::SYP => '£',
            self::SZL => 'L',
            self::THB => '฿',
            self::TJS => 'ЅМ',
            self::TMT => 'T',
            self::TND => 'د.ت',
            self::TOP => 'T$',
            self::TRY => '₺',
            self::TTD => '$',
            self::TVD => '$',
            self::TWD => 'NT$',
            self::TZS => 'TSh',
            self::UAH => '₴',
            self::UGX => 'USh',
            self::USD => '$',
            self::UYU => '$',
            self::UZS => 'UZS',
            self::VES => 'Bs',
            self::VND => '₫',
            self::VUV => 'Vt',
            self::WST => 'WS$',
            self::XAF => 'FCFA',
            self::XCD => '$',
            self::XDR => 'SDR',
            self::XOF => 'CFA',
            self::XPF => '₣',
            self::YER => '﷼',
            self::ZAR => 'R',
            self::ZMW => 'ZK',
            self::ZWL => '$',
        };
    }
}
